[phases.setup]
packages = ["php82", "composer", "zip", "unzip"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.start]
cmds = [
  "php -S 0.0.0.0:${PORT} -t public"
]
